rowlineage_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: demo
      password: demo
      port: 6543
      dbname: demo
      schema: public
      threads: 4
    clickhouse:
      type: clickhouse
      host: clickhouse
      user: demo
      password: demo
      port: 8123
      schema: demo
      threads: 4
