rowlineage_demo:
  target: dev
  outputs:
    dev:
      type: rowlineage
      base_adapter: postgres
      host: postgres
      user: demo
      password: demo
      port: 5432
      dbname: demo
      schema: public
      threads: 4
